// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Spot.Models
{
    [Table("Account")]
    public partial class Account
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required(ErrorMessage ="帳號不可為空白")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "密碼不可為空白")]
        public string Password { get; set; }
    }
}