// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Spot.Models
{
    [Table("Place")]
    public partial class Place
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required(ErrorMessage ="國家為必須要項")]
        public string Nation { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string Feature { get; set; }
       
        public string Photo { get; set; }
        [Required]
        public string Language { get; set; }
        [Required]
        public string Currency { get; set; }
        [DataType(DataType.Currency)]
        public int Budget { get; set; }
        public string Introduction { get; set; }
    }
}